use_frameworks!

platform :ios, '8.0'

target 'YHWebImage_Example' do
  pod 'YHWebImage', :path => '../'

  target 'YHWebImage_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
